name: Trigger Jenkins Pipeline

on:
  push:
    branches:
      - develop

jobs:
  execute-ci:
    runs-on: [self-hosted, linux]

    steps:

      - name: Trigger Snapshot
        if: github.ref == 'refs/heads/develop'
        uses: unit-corp/ci-templates/trigger-snapshot@main
