name: CI Trigger Release Snapshot

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  trigger-maven-release-snapshot:
    uses: unit-corp/ci-templates/.github/workflows/trigger-maven-release-snapshot.yml@main