name: CI Trigger Jenkins Job

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  trigger-jenkins:
    uses: unit-corp/ci-templates/.github/workflows/trigger-jenkins.yml@main
    secrets:
      JENKINS_MB_TOKEN: upbp-02-rms-be-token1
